### ISSUE TITLE
Got an error on execution : (Win10 Enterprise) -- SOLVED

### ISSUE THREAD

**Issue by La-Fleur** [EliteLoser/DotNetVersionLister#12]
Got an error on execution : (Win10 Enterprise)

 Get-STDotNetVersion -NoSummary
Get-STDotNetVersion : Command 'Get-STDotNetVersion' not found on module 'DotNetVersionLister', unable to load 
module. To catch more info, run 'Import-Module DotNetVersionLister'.
In row:1 char:1
+ Get-STDotNetVersion -NoSummary
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-STDotNetVersion:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule

PS C:\WINDOWS\system32> start https://go.microsoft.com/fwlink/?LinkID=135170 (to view more info)
PS C:\WINDOWS\system32> Get-ExecutionPolicy 
Restricted
PS C:\WINDOWS\system32> Get-ExecutionPolicy -List

        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy       Undefined
   UserPolicy       Undefined
      Process       Undefined
  CurrentUser       Undefined
 LocalMachine       Undefined

TO SOLVE :
 Set-ExecutionPolicy -ExecutionPolicy Unrestricted
PS C:\WINDOWS\system32> Get-STDotNetVersion
ComputerName : localhost
>=4.x        : 4.7.2
v4\Client    : Installed
v4\Full      : Installed
v3.5         : Installed
v3.0         : Installed
v2.0.50727   : Installed
v1.1.4322    : Not installed (no key)
Ping         : True
Error        :

    Script start time: 01/20/2021 16:26:34
    Script end time:   01/20/2021 16:26:34

**Comment by EliteLoser** [comment]
k
