### ISSUE TITLE
Add detection of .Net 4.8

### ISSUE THREAD

**Issue by Jon007** [EliteLoser/DotNetVersionLister#8]
see notes on
https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed

**Comment by EliteLoser** [comment]
Will pull in your request once you approve the changes. OK? Sorry about the wrong place I edited.

**Comment by Jon007** [comment]
ok thats getting interesting... my pull request was a patch and I think you've checked the version update into my master branch which I had forgotten about and is behind both your master and my patch pull request..
